### PR TITLE
Finished ui mes livres (supposedly)

### PR DESCRIPTION
**Pull request by Galaxy1221**

### CODE REVIEW

**Comment by Guibi1** [comment]
This change is [Reviewable](https://reviewable.io/reviews/Guibi1/H23-Gr3-Equipe3-Univox/69)

**Review by azomDev — COMMENTED** [review]
> Reviewed 3 of 4 files at r2, 1 of 1 files at r3, 2 of 2 files at r4, 4 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Guibi1/H23-Gr3-Equipe3-Univox/69)* status: 9 of 10 files reviewed, all discussions resolved

**Review by azomDev — APPROVED** [review]
> Reviewed 1 of 5 files at r5.
> *[Reviewable](https://reviewable.io/reviews/Guibi1/H23-Gr3-Equipe3-Univox/69)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Galaxy1221)

**Review by azomDev — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/Guibi1/H23-Gr3-Equipe3-Univox/69#-:-NVMres7Cv0--_9iUEEm:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Galaxy1221)

**Review by azomDev — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Guibi1/H23-Gr3-Equipe3-Univox/69)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Galaxy1221)

**Pull request merged**
