### PR TITLE
29 Ajouter des paramètres de l'utilisateur

### PR DESCRIPTION
**Pull request by azomwastaken**
Ajout de startWeekDate

### CODE REVIEW

**Comment by Guibi1** [comment]
This change is [Reviewable](https://reviewable.io/reviews/Guibi1/H23-Gr3-Equipe3-Univox/32)

**Review by azomwastaken — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Guibi1/H23-Gr3-Equipe3-Univox/32)* status: 0 of 33 files reviewed, 7 unresolved discussions (waiting on @Guibi1)

___
*[`src/lib/components/ScheduleView.svelte` line 47 at r1](https://reviewable.io/reviews/Guibi1/H23-Gr3-Equipe3-Univox/32#-NR3rlkH8ULYhQBCzl-_:-NR4g_DB-WkN84g9mgph:b-896fix) ([raw file](https://github.com/Guibi1/H23-Gr3-Equipe3-Univox/blob/255ac000b88f9d710ebde37534db0ab7cd34dcee/src/lib/components/ScheduleView.svelte#L47)):*
<details><summary><i>Previously, Guibi1 (Laurent Stéphenne) wrote…</i></summary><blockquote>

Est-ce que la réactivité focntionne ici?
(enlève le log)
</blockquote></details>

Done.
___
*[`src/lib/components/ScheduleView.svelte` line 54 at r1](https://reviewable.io/reviews/Guibi1/H23-Gr3-Equipe3-Univox/32#-NR3s--m4GHrgpruUW_U:-NR4gaAn77PxumptV41r:b-896fix) ([raw file](https://github.com/Guibi1/H23-Gr3-Equipe3-Univox/blob/255ac000b88f9d710ebde37534db0ab7cd34dcee/src/lib/components/ScheduleView.svelte#L54)):*
<details><summary><i>Previously, Guibi1 (Laurent Stéphenne) wrote…</i></summary><blockquote>

Il manque l'offset ici -> 6 + offset
</blockquote></details>

Done.
___
*[`src/lib/stores/startWeekDate.ts` line 18 at r1](https://reviewable.io/reviews/Guibi1/H23-Gr3-Equipe3-Univox/32#-NR3s9Yw4fo1Wdp46ie9:-NR4ge0s1ynYVREt2dgC:b-896fix) ([raw file](https://github.com/Guibi1/H23-Gr3-Equipe3-Univox/blob/255ac000b88f9d710ebde37534db0ab7cd34dcee/src/lib/stores/startWeekDate.ts#L18)):*
<details><summary><i>Previously, Guibi1 (Laurent Stéphenne) wrote…</i></summary><blockquote>

Dead code copié de colorScheme
</blockquote></details>

Done.
___
*[`src/routes/+layout.server.ts` line 5 at r1](https://reviewable.io/reviews/Guibi1/H23-Gr3-Equipe3-Univox/32#-NR3sOwj-_wMXJS0huTd:-NR4gfJo80UDXGA4MRmu:b-896fix) ([raw file](https://github.com/Guibi1/H23-Gr3-Equipe3-Univox/blob/255ac000b88f9d710ebde37534db0ab7cd34dcee/src/routes/%2Blayout.server.ts#L5)):*
<details><summary><i>Previously, Guibi1 (Laurent Stéphenne) wrote…</i></summary><blockquote>

Organise les imports
</blockquote></details>

Done.
___
*[`src/routes/(app)/parametre/+page.svelte` line 4 at r1](https://reviewable.io/reviews/Guibi1/H23-Gr3-Equipe3-Univox/32#-NR3sWwC016zHasBM0dp:-NR4ggUh5pPDdNGB0BTe:b-896fix) ([raw file](https://github.com/Guibi1/H23-Gr3-Equipe3-Univox/blob/255ac000b88f9d710ebde37534db0ab7cd34dcee/src/routes/(app)/parametre/%2Bpage.svelte#L4)):*
<details><summary><i>Previously, Guibi1 (Laurent Stéphenne) wrote…</i></summary><blockquote>

Dead code?
</blockquote></details>

Done.
___
*[`src/routes/(app)/parametre/+page.svelte` line 15 at r1](https://reviewable.io/reviews/Guibi1/H23-Gr3-Equipe3-Univox/32#-NR3sZm1-8evYH0pUpSQ:-NR4gjgz4yNR5IBu8rCL:b-896fix) ([raw file](https://github.com/Guibi1/H23-Gr3-Equipe3-Univox/blob/255ac000b88f9d710ebde37534db0ab7cd34dcee/src/routes/(app)/parametre/%2Bpage.svelte#L15)):*
<details><summary><i>Previously, Guibi1 (Laurent Stéphenne) wrote…</i></summary><blockquote>

Utilise <label>
</blockquote></details>

Done.

**Review by azomwastaken — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Guibi1/H23-Gr3-Equipe3-Univox/32)* status: 0 of 33 files reviewed, 7 unresolved discussions (waiting on @Guibi1)

___
*[`src/routes/api/settings/startWeekDate/+server.ts` line 7 at r1](https://reviewable.io/reviews/Guibi1/H23-Gr3-Equipe3-Univox/32#-NR3scB36W6ZTxx4H8eB:-NR4hmPg90qW35tlrDKZ:b-896fix) ([raw file](https://github.com/Guibi1/H23-Gr3-Equipe3-Univox/blob/255ac000b88f9d710ebde37534db0ab7cd34dcee/src/routes/api/settings/startWeekDate/%2Bserver.ts#L7)):*
<details><summary><i>Previously, Guibi1 (Laurent Stéphenne) wrote…</i></summary><blockquote>

Arrange l'erreur
</blockquote></details>

Done.

**Review by Guibi1 — APPROVED** [review]
> Reviewed 24 of 33 files at r2, 9 of 9 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/guibi1/h23-gr3-equipe3-univox/32)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @azomwastaken)

**Review by Guibi1 — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/guibi1/h23-gr3-equipe3-univox/32)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @azomwastaken)

**Pull request merged**
