### PR TITLE
Groupes d'amis

### PR DESCRIPTION
**Pull request by Virliott**
À priori fonctionnel:
- Groupes (renommer, supprimer, afficher l'horaire commun)
- Affichages des horaires communs des amis

À faire (je pourrais peut-être m'en occuper):
- Reformater les « périodes libres » des horaires combinés (échanger les « trous » et les « périodes libres »)

### CODE REVIEW

**Comment by Guibi1** [comment]
This change is [Reviewable](https://reviewable.io/reviews/Guibi1/H23-Gr3-Equipe3-Univox/70)

**Review by Guibi1 — CHANGES_REQUESTED** [review]
> Reviewed 6 of 11 files at r1, 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Guibi1/H23-Gr3-Equipe3-Univox/70)* status: all files reviewed, 8 unresolved discussions (waiting on @Virliott)

___
*[`src/lib/commonAvailabilities.ts` line 5 at r2](https://reviewable.io/reviews/Guibi1/H23-Gr3-Equipe3-Univox/70#-NV70FCv4xJ9kl5DwC2g:-NV70FCv4xJ9kl5DwC2h:bfrjcz3) ([raw file](https://github.com/Guibi1/H23-Gr3-Equipe3-Univox/blob/05e7beff70075c15fe54309e81999fc17dfd64b4/src/lib/commonAvailabilities.ts#L5)):*
> ```XML
> import { Types } from "mongoose";
> 
> export function getWeekCommonAvailabilities(week: Dayjs, periods: Period[]): Schedule {
> ```

Ajoute de la doc plz
___
*[`src/lib/commonAvailabilities.ts` line 76 at r2](https://reviewable.io/reviews/Guibi1/H23-Gr3-Equipe3-Univox/70#-NV70Mep3jxhuJeMuhQf:-NV70Mep3jxhuJeMuhQg:b-o3ma2m) ([raw file](https://github.com/Guibi1/H23-Gr3-Equipe3-Univox/blob/05e7beff70075c15fe54309e81999fc17dfd64b4/src/lib/commonAvailabilities.ts#L76)):*
> ```XML
>  * @returns {Period[]} An array of periods representing the common availabilities for the given day.
>  */
> export function getCommonOccupied(date: Dayjs, periods: Period[]): Period[] {
> ```

Fait une fonction pour le week occupied
___
*[`src/lib/Types.ts` line 36 at r2](https://reviewable.io/reviews/Guibi1/H23-Gr3-Equipe3-Univox/70#-NV78snb6RKGitT0Wzwb:-NV78snb6RKGitT0Wzwc:bmxvtib) ([raw file](https://github.com/Guibi1/H23-Gr3-Equipe3-Univox/blob/05e7beff70075c15fe54309e81999fc17dfd64b4/src/lib/Types.ts#L36)):*
> ```XML
>     name: string;
>     usersId: Types.ObjectId[];
>     horaireCommun: Schedule;
> ```

Nop il faut fetch l'horaire commun à chaque fois. Enlève cette variable et utilise la fonction de db.ts à la place.
___
*[`src/routes/(app)/amis/+page.svelte` line 42 at r2](https://reviewable.io/reviews/Guibi1/H23-Gr3-Equipe3-Univox/70#-NV79tE213FqTtQ5w2Jl:-NV79tE213FqTtQ5w2Jm:b-nz1lht) ([raw file](https://github.com/Guibi1/H23-Gr3-Equipe3-Univox/blob/05e7beff70075c15fe54309e81999fc17dfd64b4/src/routes/(app)/amis/%2Bpage.svelte#L42)):*
> ```Svelte
>         const params = new URLSearchParams($page.url.searchParams);
>         params.set("friendId", friend._id.toString());
>         params.delete("commonSchedule"); //AJOUT
> ```

Enlève ces commentaires
___
*[`src/routes/(app)/amis/+page.svelte` line 98 at r2](https://reviewable.io/reviews/Guibi1/H23-Gr3-Equipe3-Univox/70#-NV7A11h3WIh_q5MiUY6:-NV7A11iEG9sblB0sOgw:b-azo9m3) ([raw file](https://github.com/Guibi1/H23-Gr3-Equipe3-Univox/blob/05e7beff70075c15fe54309e81999fc17dfd64b4/src/routes/(app)/amis/%2Bpage.svelte#L98)):*
> ```Svelte
>                             <Option
>                                 text="Horaire libre commun"
>                                 onClick={() => console.log("TODO: afficher l'horaire")}
> ```

Clean up plz
___
*[`src/routes/(app)/amis/+page.server.ts` line 30 at r2](https://reviewable.io/reviews/Guibi1/H23-Gr3-Equipe3-Univox/70#-NV7AYEJ7gguXXYVmdFe:-NV7AYEJ7gguXXYVmdFf:bi6ycen) ([raw file](https://github.com/Guibi1/H23-Gr3-Equipe3-Univox/blob/05e7beff70075c15fe54309e81999fc17dfd64b4/src/routes/(app)/amis/%2Bpage.server.ts#L30)):*
> ```XML
>                     const memberSchedule = scheduleFromJson(await db.getSchedule(user));
> 
>                     membersCombinedPeriods.push(...memberSchedule.periods);
> ```

Met tout le if en une ligne
___
*[`src/routes/(app)/amis/+page.server.ts` line 52 at r2](https://reviewable.io/reviews/Guibi1/H23-Gr3-Equipe3-Univox/70#-NV7Ahbz8RfeG3RmZNU0:-NV7Ahbz8RfeG3RmZNU1:b-1fp0px) ([raw file](https://github.com/Guibi1/H23-Gr3-Equipe3-Univox/blob/05e7beff70075c15fe54309e81999fc17dfd64b4/src/routes/(app)/amis/%2Bpage.server.ts#L52)):*
> ```XML
>                 const usersCombinedPeriods: Period[] = [];
>                 const friendScheduleToCompare = scheduleFromJson(await db.getSchedule(friend));
>                 const localUserSchedule = scheduleFromJson(await db.getSchedule(locals.user));
> ```

Pas besoin d'appeler scheduleFromJson lorsque le code est server side
___
*[`src/routes/(app)/amis/+page.server.ts` line 63 at r2](https://reviewable.io/reviews/Guibi1/H23-Gr3-Equipe3-Univox/70#-NV7AoKWENc-LitZX2T8:-NV7AoKWENc-LitZX2T9:b67f8wv) ([raw file](https://github.com/Guibi1/H23-Gr3-Equipe3-Univox/blob/05e7beff70075c15fe54309e81999fc17dfd64b4/src/routes/(app)/amis/%2Bpage.server.ts#L63)):*
> ```XML
>                     getWeekCommonAvailabilities(dayjs(), usersCombinedPeriods)
>                 );
>                 console.log(friendCommonSchedule)
> ```

Cleanup

**Review by Guibi1 — COMMENTED** [review]
Très bien. Il faut cleanup bcp mais good job!

> *[Reviewable](https://reviewable.io/reviews/Guibi1/H23-Gr3-Equipe3-Univox/70#-:-NV7B21j5v6zr3Cx25wD:b-jpoqgh)* status: all files reviewed, 8 unresolved discussions (waiting on @Virliott)

**Review by Guibi1 — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/Guibi1/H23-Gr3-Equipe3-Univox/70)* status: 10 of 11 files reviewed, 3 unresolved discussions (waiting on @Virliott)

___
*[`src/routes/(app)/amis/+page.server.ts` line 52 at r2](https://reviewable.io/reviews/Guibi1/H23-Gr3-Equipe3-Univox/70#-NV7Ahbz8RfeG3RmZNU0:-NVFATzd6WU6CgbVlKP9:b-zb6rkx) ([raw file](https://github.com/Guibi1/H23-Gr3-Equipe3-Univox/blob/05e7beff70075c15fe54309e81999fc17dfd64b4/src/routes/(app)/amis/%2Bpage.server.ts#L52)):*
<details><summary><i>Previously, Guibi1 (Laurent Stéphenne) wrote…</i></summary><blockquote>

Pas besoin d'appeler scheduleFromJson lorsque le code est server side
</blockquote></details>

Aussi pas besoin de push. Fait un one liner dans le getWeekCommonAvailabilities

**Comment by Virliott** [comment]
Comme ça genre ?
image

**Comment by Guibi1** [comment]
Utilise le spread operator. Donc comme ça :
[...friendSchedule.periods, ...friendSchedule.classes]

**Comment by Virliott** [comment]
Ça roule;
Donc ça c'est fortiche
image

Et la variable « horaireCommun » était même pas utilisée de toute façon, donc je l'ai juste virée

**Review by Guibi1 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/guibi1/h23-gr3-equipe3-univox/70#-:-NVFVJy81et8wF5c-OAn:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @Virliott)

**Review by Guibi1 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/guibi1/h23-gr3-equipe3-univox/70)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Virliott)

**Pull request merged**
