### PR TITLE
Pouvoir delete periodes

### PR DESCRIPTION
**Pull request by azomDev**

### CODE REVIEW

**Comment by Guibi1** [comment]
This change is [Reviewable](https://reviewable.io/reviews/Guibi1/H23-Gr3-Equipe3-Univox/73)

**Comment by azomDev** [comment]
oops just dont accept yet I pr'ed the wrong branch

**Review by Guibi1 — APPROVED** [review]
> Reviewed 3 of 15 files at r3, 1 of 1 files at r4, 1 of 2 files at r5, 4 of 5 files at r6, 4 of 6 files at r7, 9 of 9 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Guibi1/H23-Gr3-Equipe3-Univox/73)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @azomDev)

**Review by Guibi1 — DISMISSED** [review]
> Reviewed 12 of 12 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/guibi1/h23-gr3-equipe3-univox/73)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @azomDev)

**Review by Guibi1 — APPROVED** [review]
> Reviewed 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/guibi1/h23-gr3-equipe3-univox/73)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @azomDev)

**Pull request merged**
